### ISSUE TITLE
Merging with gff3-capable fork of 2.2.0 version?

### ISSUE THREAD

**Issue by mmokrejs** [nathanweeks/exonerate#24]
Hi Nathan,

1.
  are you aware of this forked repo?

https://github.com/hotdogee/exonerate-gff3 which is an improved version of exonerate-2.2.0 with GFF3 format output support

Maybe you could unite the efforts.

2.
  Some patches and compile/install tricks can be inferred from the ebuild
https://data.gpo.zugaina.org/science/sci-biology/exonerate-gff3
https://cgit.gentoo.org/proj/sci.git/tree/sci-biology/exonerate-gff3/files/exonerate-gff3-9999-asneeded.patch?id=d209b24ac3b9de78f7048fb76467c42bad604263 # well this patch chnages the part you commented out but 

3.
There is also an on-top utility https://github.com/lufuhao/ExonerateTransferAnnotation .

4.
There is a similar utility https://cgit.gentoo.org/proj/sci.git/commit/sci-biology/ESTate/ESTate-0.5.ebuild?id=4c181b3959260dbe65d3801005b99f1a6e4db33c

**Comment by nathanweeks** [comment]
> are you aware of this forked repo?
> 
> https://github.com/hotdogee/exonerate-gff3 which is an improved version of exonerate-2.2.0 with GFF3 format output support
> 
> Maybe you could unite the efforts.

Thanks @mmokrejs, I was not aware of that repo. It can be possible to post-process exonerate output to get GFF3 (e.g., 
https://github.com/nathanweeks/exonerate/issues/14#issuecomment-373154847 ), but having the capability built-in would be more convenient. I'm happy to accept PRs (or provide PRs for features/fixes made in this exonerate repo to another exonerate fork).

> 
> Some patches and compile/install tricks can be inferred from the ebuild https://data.gpo.zugaina.org/science/sci-biology/exonerate-gff3 https://cgit.gentoo.org/proj/sci.git/tree/sci-biology/exonerate-gff3/files/exonerate-gff3-9999-asneeded.patch?id=d209b24ac3b9de78f7048fb76467c42bad604263 # well this patch chnages the part you commented out but

Thanks for the tips. The pthreads code was commented out due to data races in exonerate when multiple threads are used. 

> 
> There is also an on-top utility https://github.com/lufuhao/ExonerateTransferAnnotation .
> 
> 
> There is a similar utility https://cgit.gentoo.org/proj/sci.git/commit/sci-biology/ESTate/ESTate-0.5.ebuild?id=4c181b3959260dbe65d3801005b99f1a6e4db33c

I wasn't aware of either tool. I appreciate the links!
