### ISSUE TITLE
`aclocal-1.4' is needed during the  process of installation

### ISSUE THREAD

**Issue by luwd401** [nathanweeks/exonerate#25]
Hello, I get an error when I run 'make' during the process of installation.

My linux system:
Kernel Version: 5.15.0-58-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8

Operating process:
$ git clone https://github.com/nathanweeks/exonerate.git
$ cd exonerate
$ ./configure
$ make
cd . && /home/howard/software/exonerate/missing aclocal-1.4
WARNING: `aclocal-1.4' is needed, and you do not seem to have it handy on your
         system.  You might have modified some files without having the
         proper tools for further handling them.  Check the `README' file,
         it often tells you about the needed prerequirements for installing
         this package.  You may also peek at any GNU archive site, in case
         some other package would contain this missing `aclocal-1.4' program.
make: *** [Makefile:108：aclocal.m4] error 1

Thank you!

**Comment by nathanweeks** [comment]
I'm guessing that `git checkout v2.4.0` was executed before `./configure` (otherwise the configure script wouldn't exist)? If so, could you try `autoreconf -i` before `./configure`? This is similar to the directions for building directly from the master branch as described in the README.md (which is the recommended way to build exonerate to get bug fixes):
https://github.com/nathanweeks/exonerate/blob/22beeb0249cb8e721813af02e489718ba84e5482/README.md?plain=1#L28-L34

**Comment by luwd401** [comment]
Thank you very much for your quick response! Accidentally, I went to the src folder and saw a makefile document. I tried to run 'make' at the src folder and it worked. 

$ git clone https://github.com/nathanweeks/exonerate.git 
$ cd exonerate 
$ ./configure [MY_CONFIGURE_OPTIONS] 
$ cd src
$ make
$ make check
$ sudo make install

A very nice tool! Good luck!
I hope my experience will be helpful to others who encounter the same problem.
