### ISSUE TITLE
could not open substitution matrix

### ISSUE THREAD

**Issue by songjiax** [nathanweeks/exonerate#32]

**Comment by nathanweeks** [comment]
Could you provide an example command that reproduces the error?

**Comment by songjiax** [comment]
Hello,

The error when running is: ** FATAL ERROR **: Could not open substitution
matrix [TRUE] exiting...

I searched and found that the replacement matrix was not provided in the
software directory, and there was no parameter to specify the matrix
position...
my command：

Thanks！

Nathan Weeks ***@***.***> 于 2024年12月8日周日 00:10写道：

**Comment by nathanweeks** [comment]
The command didn't make it into the GitHub issue comment; could you try copying/pasting it into a [fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) in the GitHub issue?

**Comment by songjiax** [comment]
sorry, there are some problems in my github, below is my command: exonerate -options --model cdna2genome --forwardcoordinates FALSE --exhaustive FALSE --softmasktarget TRUE --score 500 --saturatethreshold 100 --dnawordlen 15 --codonwordlen 15 --dnahspthreshold 60 --bestn 1 --maxintron 150000 --querytype dna --targettype genome --query gencode.v35.transcripts.fa --target /public/home/daishanshan/song/data/RNA-seq/00_ref/chm13v1.1_hg002XYv2.7.fasta > transcript_alignment_results.sam

**Comment by nathanweeks** [comment]
> ` exonerate -options `

Try removing `-options`, and specifying `--targettype dna` (instead of `--targettype genome`, as `--targettype` option-argument must be either "dna" or "protein").

The `-options` argument is apparently being interpreted as a set of short (single-letter) options (e.g., `-o -p -t -i -o -n -s`), as is conventional for most Unix command-line utilities. Somehow the option-argument for `-p / --proteinsubmat` is being paired with the subsequent `TRUE` option argument. exonerate has its own custom argument parser (not POSIX `getopt()` or common extension `getopt_long()`), and I haven't investigated to see how it permutes the arguments.

**Comment by songjiax** [comment]
I just wanted to say a huge thank you for the updates you made to the code. They’ve been super helpful! Thanks a ton!

**Comment by nathanweeks** [comment]
Thanks!
