### ISSUE TITLE
error: 'JobQueue' has no member named 'job_func'

### ISSUE THREAD

**Issue by sagitter** [nathanweeks/exonerate#8]
Hi all,

`exonerate-2.4.0` compile fails on fedora 23 with this error:

```
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"exonerate\" -DVERSION=\"2.4.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_ERRNO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRINGS_H=1 -DHAVE_CTYPE_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_TIME_H=1 -DHAVE_UNISTD_H=1 -I. -I.  -DSOURCE_ROOT_DIR="\"/home/sagitter/rpmbuild/BUILD/exonerate-2.4.0\""            -DCUSTOM_GUINT64_FORMAT="\"lu\""            -I../../src/struct    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z,relro -fPIC -pie -Wl,-z,now -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -c jobqueue.c
jobqueue.c: In function 'JobQueue_Task_free_func':
jobqueue.c:83:5: warning: implicit declaration of function 'JobQueue_Task_destroy' [-Wimplicit-function-declaration]
     JobQueue_Task_destroy(task);
     ^
jobqueue.c: In function 'JobQueue_submit':
jobqueue.c:109:7: error: 'JobQueue {aka struct <anonymous>}' has no member named 'job_func'
     jq->job_func(job_data); /* when no threads available, just run the job */
       ^
jobqueue.c: At top level:
jobqueue.c:81:13: warning: 'JobQueue_Task_free_func' defined but not used [-Wunused-function]
 static void JobQueue_Task_free_func(gpointer data, gpointer user_data){
             ^
Makefile:174: recipe for target 'jobqueue.o' failed
```

Full build log: http://fpaste.org/344263/
GCC-5.3.1

**Comment by nathanweeks** [comment]
It looks like, despite specifying the --enable-pthreads configure option, that the "-DUSE_PTHREADS" compiler option isn't being specified at compile time. I don't have a Fedora Core 23 VM to test with, but after a simple "./configure" on FreeBSD 9.3, here's the first compiler command I see while executing "make":

```
gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"exonerate\" -DVERSION=\"2.4.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_ERRNO_H=1 -DHAVE_MATH_H=1 -DHAVE_STRINGS_H=1 -DHAVE_CTYPE_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_TIME_H=1 -DHAVE_UNISTD_H=1 -I. -DCUSTOM_GUINT64_FORMAT="\"llu\""    -g -O2 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include   -DG_DISABLE_ASSERT -O3 -finline-functions -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_PTHREADS -MT fsm.test.o -MD -MP -MF .deps/fsm.test.Tpo -c -o fsm.test.o fsm.test.c
```

I've only gotten that error for the v2.4.0 release when compiling with --disable-pthreads (that particular bug was fixed in the development version: https://github.com/nathanweeks/exonerate/commit/e807454f35513475192e27e66b15d10ef324a83b). 

That said, the performance benefit I observed using multiple threads with the exonerate client seemed minimal due to the approach used---and it's much faster to start an exonerate-server with the given reference sequence and issue one query sequence per exonerate client invocation (I had an elaborate wrapper script that did this automatically with a multi-FASTA file). In addition, the multi-threaded exonerate-server had race-condition bugs exposed at high thread counts, so I disabled pthreads in the development version of exonerate (which needs the above patch to compile). Unfortunately, the non-threaded exonerate-server (which forks multiple processes to handle requests instead) had a few race conditions of its own, which were addressed in the development version in the following commit: https://github.com/nathanweeks/exonerate/commit/b2acb3fa9ed305853b228c33c9469d9664f0c9d6

**Comment by sagitter** [comment]
Okay.
Compile fixed by applying your patch (https://github.com/nathanweeks/exonerate/commit/e807454f35513475192e27e66b15d10ef324a83b + https://github.com/nathanweeks/exonerate/commit/b2acb3fa9ed305853b228c33c9469d9664f0c9d6) and by disabling `multi-threading`.

I take advance of this discussion to inform that `exonerate` has been included in [official repositories of the Fedora Project](https://admin.fedoraproject.org/pkgdb/package/rpms/exonerate/).

Many thanks.
